name: eisenhower_matrix
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1
  http: ^1.2.2
  provider: ^6.0.5
  shared_preferences: ^2.3.3
  intl: ^0.19.0
  flutter_dotenv: ^5.2.1
  lottie: ^3.1.3
  flutter_launcher_icons: ^0.13.1
  google_mobile_ads: ^5.2.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"


flutter:
  assets:
    - assets/app_icon.png
    - assets/reminder.png
    - .env
    - assets/animations/loading_animation.json

  uses-material-design: true



